### ISSUE TITLE
Некорректный парсинг адреса, если адрес не содержит адрес дома

### ISSUE THREAD

**Issue by pgavrilov** [micronull/JOSM-Russia-address-helper-plugin#1]
Домик: https://www.openstreetmap.org/way/193672975
Результат запроса в ЕГРН:
addr:full=Московская область, г Руза, д Марс
addr:housenumber=Марс
addr:source=ЕГРН
addr:street=г Руза
________

Версия плагина 0.1.1 (в JOSM), однако скачивалась из latest в момент, когда последней была 0.1.2, возможно это ошибка номера версии в коде плагина.

**Comment by micronull** [comment]
> Версия плагина 0.1.1 (в JOSM), однако скачивалась из latest в момент, когда последней была 0.1.2, возможно это ошибка номера версии в коде плагина.

Ты видимо попал в тот момент когда запушил тег релиза, а саму сборку ещё не загрузил. Попробуй скачать снова. Я проверил, у меня отобразилась 0.1.2 версия.

**Comment by micronull** [comment]
На данный момент адреса парсятся с помощью регулярных выражений.
Раньше они просто бились через запятую и последний элемент считался номером дома, поэтому вылазил этот баг. Сейчас это исключено из-за строгих правил в регулярных выражениях.
