### ISSUE TITLE
Некорректная разборка адресов, включающих и дом, и участок

### ISSUE THREAD

**Issue by literannn** [micronull/JOSM-Russia-address-helper-plugin#10]
addr:RU:egrn=обл. Ленинградская, р-н Приозерский, с/пос. Сосновское, массив Орехово-Северное, ДПК Светлана, 3-ий Цветочный переулок, дом 16, уч. № 306

разбирается как:

addr:housenumber=306
addr:street=3-й Цветочный переулок

хотя должен бы подхватывать именно дом

**Comment by TakutoRU** [comment]
Попробуем что-то с этим сделать.

сб, 29 июл. 2023 г. в 15:34, literannn ***@***.***>:

**Comment by TakutoRU** [comment]
будет поправлено в след. релизе.
но тут надо понимать, что разбирает адреса машина, а пишет их человек. Разобрать 100% адресов, написанных всеми возможными способами, не получится никогда. К тому же, писать участок ПОСЛЕ дома, ИМХО, некорректно.

**Comment by literannn** [comment]
Спасибо!
Я прекрасно понимаю, что идеал неосуществим, но немножко ближе к нему стать можно))

Пока никак не продвигается в сторону разборки адресов, адресуемых по деревне (без улиц)?

**Comment by micronull** [comment]
@literannn правильно ли понимаю, что отсутствие названий улиц в таких населенных пунктах как деревни, это нормальное явление? 

У нас в плагине стоит обязательное наличие названий улиц в данных ОСМ.

**Comment by micronull** [comment]
Можно сделать чтоб не создавался тег `addr:street`, если не удалось распарсить улицу и на близжайшей линии отмеченной как `highway` так же нет названия.

Просто хочется чтоб плагин заполнял только 100% распознанные адреса согласно соглашению https://wiki.openstreetmap.org/wiki/RU:%D0%90%D0%B4%D1%80%D0%B5%D1%81%D0%B0#%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F

**Comment by TakutoRU** [comment]
Когда я соберусь с силами (а это обязательно случится) и выпну релиз, в нем
будет разбор адресов без улицы (по addr:place). Это уже реализовано, но
баги точно будут.

вт, 1 авг. 2023 г. в 14:05, Stepan I. ***@***.***>:

**Comment by literannn** [comment]
@micronull это не то чтобы нормальное, а очень распространенное явление. В большинстве небольших деревень нет именованных улиц.

Первый пришедший в голову пример рядом с Москвой https://www.openstreetmap.org/edit#map=17/55.89295/37.15644

**Comment by micronull** [comment]
@TakutoRU было бы не плохо, если бы ты свои правки залил как отдельную ветку. Мы бы самостоятельно собрали эту версию и потыкали бы её)

**Comment by Ctrogo** [comment]
Здравствуйте, а подтягивать название улиц с ЕГРН планируете? А то вроде все подписал, а раз и ошибка - одну улицу пропустил :(

**Comment by TakutoRU** [comment]
Не очень понятно, о какой именно проблеме речь. Но вообще подтягивать
названия улиц напрямую из ЕГРН нельзя, они там не соответствуют правилам
ОСМ. Сейчас в бета-тестировании новая версия плагина, ознакомиться можно
тут: https://t.me/+ZNw0BIhX1xMxZDBi

чт, 14 сент. 2023 г., 16:44 Ctrogo ***@***.***>:

**Comment by TakutoRU** [comment]
часть проблем решена в 0.9.0.0, полный разбор всех частей адреса и правила присвоения планируются к разработке.
