### ISSUE TITLE
Один и тот же токен попадает и в название улицы, и в номер дома

### ISSUE THREAD

**Issue by alexey-zakharenkov** [micronull/JOSM-Russia-address-helper-plugin#17]
Координаты: 56.0770279, 37.4847668.

Через пункт меню "Для выделенных объектов" плагин не обрабатывает дом с адресами:
- в слое участков: обл. Московская, р-н Дмитровский, п. Некрасовский, пер. 5-ый, дом 5
- в слое ОКС: Российская Федерация, Московская область, городской округ Дмитровский, поселок Некрасовский, пер. 5-ый

Через пункт меню "На месте клика" первый адрес парсится в нормальную пару тегов:
```
addr:housenumber=5
addr:street=5-й переулок
```
другой - в не очень:
```
addr:housenumber=5Ы
addr:street=5-й переулок
```

По логике, если пятёрка уже вошла в название элемента улично-дорожной сети, то в номер дома она не должна попасть.

**Comment by TakutoRU** [comment]
Такая проверка есть, но работала некорректно. Будет исправлено в следующем релизе.

**Comment by TakutoRU** [comment]
Попытка исправления в 0.9.3.
