### ISSUE TITLE
дом №15А, строение №1

### ISSUE THREAD

**Issue by alexey-zakharenkov** [micronull/JOSM-Russia-address-helper-plugin#18]
Координаты: 56.0754985, 37.4844614

Адрес: Российская Федерация, Московская область, Дмитровский городской округ, рабочий посёлок Некрасовский, ул. Южная, дом №15А, строение №1

парсится в теги
```
addr:housenumber=1
addr:street=Южная улица
```

Правильный ответ:
```
addr:housenumber=15А с1
addr:street=Южная улица
```

**Comment by TakutoRU** [comment]
Будет исправлено в предстоящем релизе.

**Comment by TakutoRU** [comment]
Исправлено в 0.9.3
