### ISSUE TITLE
"уч.22, ГП-1" парсится в addr:housenumber=1

### ISSUE THREAD

**Issue by alexey-zakharenkov** [micronull/JOSM-Russia-address-helper-plugin#19]
Координаты: 55.6536848, 36.9630852

Адрес: _обл. Московская, р-н Одинцовский, с/о Захаровский, д. Захарово, уч. 22, ГП-1_

Парсится в
```
addr:housenumber=1
addr:place=Захарово
```

55.65439, 36.9607168. Аналогичный адрес, где ГП-1 и участок идут в другом порядке:
_обл. Московская, р-н Одинцовский, д. Захарово, ГП-1, уч.4_
Опять же, плагин прописывает addr:housenumber=1

ГП, если я правильно понимаю, это "городской посёлок", в любом случае из токена "ГП-1" не надо извлекать номер дома.

Номер участка не всегда совпадает с номером дома. Есть практика в таких случаях формировать тег вида addr:housenumber=уч22, но стоит ли так делать, лучше обсудить с сообществом.

**Comment by TakutoRU** [comment]
Пока нет понимания, куда в ОСМ должен идти адрес участка, с такими адресами непонятно что делать. Плагин пытается добыть номер дома, и если запретить ему тянуть номер дома без префикса "дом" или "д", отвалится масса адресов которые записаны в простой форме "улица Пушкина, 22". Пока закрываю.

**Comment by TakutoRU** [comment]
Как вариант костыля, планируется настраиваемый список строк, которые будут отфильтровываться из входных данных. Т.е можно выкусывать "ГП-1" до парсинга адреса. Но не в следующем релизе.

**Comment by alexey-zakharenkov** [comment]
А вообще есть распространённые кейсы написания адреса, где номер дома прячется в подстроке вида "строка дефис число" без пробелов? Если нет, то из потенциальных источников номера дома надо исключать все подстроки типа ГП-1 по регулярному выражению. Возможно, просто число с минусом не рассматривать как номер дома.
