### ISSUE TITLE
Использование участка

### ISSUE THREAD

**Issue by luiswoo** [micronull/JOSM-Russia-address-helper-plugin#20]
Пункт "Разрешенное использование" указывающий на использование участка не был добавлен по каким соображениям?
Он был бы очень кстати, в режиме "На месте клика", что бы понять, для чего участок используется.

**Comment by TakutoRU** [comment]
Он не был добавлен по тем соображениям, что в запросе по координатам это поле не возвращается. Расширенная информация по участку/строению возвращается только в запросе к ПКК по коду егрн, которого наш плагин (пока?) делать не умеет.
