### ISSUE TITLE
Плагин не находит квартал

### ISSUE THREAD

**Issue by alexey-zakharenkov** [micronull/JOSM-Russia-address-helper-plugin#21]
53.2952221, 50.284346

Адрес парсится:
```
addr:RU:egrn=Самарская область, г. Самара, р-н. Красноглинский, п. Мехзавод, кв-л. 8-й, д. 8
addr:RU:egrn_type=PARCEL
addr:RU:extracted_place_name=8-й
addr:RU:extracted_place_type=квартал
addr:RU:extracted_street_name=
addr:RU:parsed_flats=
addr:RU:parsed_housenumber=8
```

но возникает ошибка "ЕГРН не найдено место: квартал 8-й"

Хотя существует и загружен в JOSM мультиполигон https://www.openstreetmap.org/relation/17442992 с тегами `place=quarter + name=8-й квартал`.

**Comment by TakutoRU** [comment]
упущение в наборе тэгов для квартала. Будет исправлено в след. релизе.

**Comment by TakutoRU** [comment]
Исправлено в 0.9.3
