### ISSUE TITLE
"аллея" вместо "квартал"

### ISSUE THREAD

**Issue by alexey-zakharenkov** [micronull/JOSM-Russia-address-helper-plugin#22]
53.2951468, 50.2841181

Адрес участка по ЕГРН: Самарская область, г. Самара, р-н. Красноглинский, п. Мехзавод, кв-л. 8-й, д. 8

Плагин выдаёт ошибку "ЕГРН улица не найдена: аллея 8".
Улица/место должно парситься в "квартал 8-й" или "8-й квартал", но не "аллея 8".

**Comment by TakutoRU** [comment]
ошибка в регекспе для аллеи, не учитывает разделитель. будет исправлено в следующем релизе.

**Comment by TakutoRU** [comment]
Исправлено в 0.9.3
