### ISSUE TITLE
загрузка адресов без улиц

### ISSUE THREAD

**Issue by literannn** [micronull/JOSM-Russia-address-helper-plugin#7]
Очень, очень не хватает возможности подчитки объектов, адресуемых по названию населенного пункта, без улиц. Есть ли надежда на появление такого функционала?

**Comment by TakutoRU** [comment]
Да, я в курсе что есть такая проблема, но сроков назвать не могу. Вы первый пользователь который вообще проявил заинтересованность, кроме меня самого )
Сейчас в планах переработка механизма обработки результатов, будут через валидатор. Потом попробую сделать адресацию по не-улицам.

**Comment by literannn** [comment]
судя по количеству домиков с тегами addr:RU:egrn (которые недавно централизованно вычищали) по всей стране, пользуются плагином уже многие

**Comment by TakutoRU** [comment]
адреса по деревням, селам, поселкам, микрорайонам и кварталам добавлены в релизе 0.9.0.0
