### ISSUE TITLE
Необходимо вынести в настройки отключение проверки SSL

### ISSUE THREAD

**Issue by micronull** [micronull/JOSM-Russia-address-helper-plugin#8]
Некоторые пользователи грузят ssl ключ в хранилище java, что является более правильным подходом.

Необходимо добавить в настройках галочку для включения и выключения веритификации ssl.

**Comment by TakutoRU** [comment]
Реализовано в коде, будет выпущено в следующем релизе.

**Comment by micronull** [comment]
Привет, @TakutoRU. Распиши пожалуйста changelog когда будешь делать релиз.

И я думаю начать вести `CHANGELOG.md`. Ты что думаешь?

**Comment by TakutoRU** [comment]
Не знаю что это такое )

пт, 2 июн. 2023 г. в 13:13, Stepan I. ***@***.***>:
